### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by Regiux** [faintpixel/skdRefSite#12]
Hi there, just wondering where I can help by uploading images to enchance the estructure and vegetation references!

**Comment by faintpixel** [comment]
Hey there. I **think** user uploads should work now, though I haven't had time to fully test it. 

If you'd like to try it out you can go to the site (http://beta.sketchdaily.net), login with a google or facebook account (that's all I've enabled for now), and then you should have an option to add images.

If you do try it, I'd suggest splitting your image into smallish sets (< 20 images)

**Comment by Regiux** [comment]
Thanks ! I´ll try my best at helping!

**Comment by olgabaranov** [comment]
The file upload page says the following: 'Currently we're only accepting people pictures (full body, heads, and hands).'
Is that current? Otherwise I would consider submitting some vegetation / structure refs.   

(Sorry to post in a closed issue, but I didn't want to open a new for that.)
