### ISSUE TITLE
Native windows app

### ISSUE THREAD

**Issue by one-thunder** [faintpixel/skdRefSite#33]
Can you make a native windows app, or can I make it and point to your API?

**Comment by faintpixel** [comment]
That's not really something I have the time or desire to work on personally, but if you'd like to take it on you're more than welcome.

The API has swagger setup, so you can take a look at what's available here: [http://reference.sketchdaily.net:4000/swagger](http://reference.sketchdaily.net:4000/swagger). Between that and looking at the requests being made by the browser it should be pretty straightforward to use hopefully. If you run into issues or have questions feel free to ask.

**Comment by one-thunder** [comment]
Ok thanks, Ill see if backend api will suit my needs, if not ill  make a node.js once. ty
